### ISSUE TITLE
case sensitive issues?

### ISSUE THREAD

**Issue by Jonathan34** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#55]
Hi,

Using the c++ community plug-in, the msbuild tasks 1.9.6, sonarqube 5.6, and under TFS 2015 environement, i get the following:
**For coverage** (using vs coverage as coveragexml where evrything is lower case):

`DEBUG: Cannot find the file 'C:\TFS\Builds\Agent404_01\1\s\Common\Utility\EventSource.h', ignoring coverage measures`

**For Vera++** analysis (it seems):

```
DEBUG: Parsing 'Vera++' format
INFO: Cannot find the file 'C:\TFS\Builds\Agent404_01\1\s\Acidizing\Fluids\ServiceUtility.cpp', skipping violations
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 3:19.649s
INFO: Final Memory: 48M/148M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Cannot feed the data into sonar, details: 'com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <file>
 at [row,col {unknown-source}]: [2120,0]'
    at org.sonar.plugins.cxx.utils.CxxReportSensor.analyse(CxxReportSensor.java:133)
    at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
    at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
    at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
    at org.sonarsource.scanner.cli.Main.main(Main.java:60)
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <file>
 at [row,col {unknown-source}]: [2120,0]
    at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:685)
    at com.ctc.wstx.sr.BasicStreamReader.throwUnexpectedEOF(BasicStreamReader.java:5519)
    at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2722)
    at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
    at org.codehaus.staxmate.in.SMHierarchicCursor.getNext(SMHierarchicCursor.java:79)
    at org.sonar.plugins.cxx.veraxx.CxxVeraxxSensor$1.stream(CxxVeraxxSensor.java:90)
    at org.sonar.api.utils.StaxParser.parse(StaxParser.java:115)
    at org.sonar.api.utils.StaxParser.parse(StaxParser.java:95)
    at org.sonar.api.utils.StaxParser.parse(StaxParser.java:85)
    at org.sonar.plugins.cxx.veraxx.CxxVeraxxSensor.processReport(CxxVeraxxSensor.java:110)
    at org.sonar.plugins.cxx.utils.CxxReportSensor.analyse(CxxReportSensor.java:111)
    ... 30 more
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
Process returned exit code 1
The SonarQube Scanner did not complete successfully
11:40:34.122  Creating a summary markdown file...
Post-processing failed. Exit code: 1
 : Failed. Check Log
 Failed analyze project, check log
```

checking the vera report it looks like this (2119 lines)

```
<checkstyle version="5.0">
<file name="C:\TFS\Builds\Agent404_01\1\s\Acidizing\Fluids\ServiceUtility.cpp">
<error line="1" severity="warning" message="no copyright notice found" source="T013"/>
<error line="2472" severity="warning" message="horizontal tab used" source="L002"/>
```

it does not close the file and checkstyle tags. but also sometimes it does not find the file (it does exists):

```
2016-07-29T16:39:38.0071800Z INFO: Processing report 'C:\TFS\Builds\Agent404_01\1\s\Acidizing\.cxxresults\reports-rats\rats-result-Acidizing-190.xml'
2016-07-29T16:39:38.0071800Z DEBUG: Parsing 'RATS' format
2016-07-29T16:39:38.0071800Z INFO: Cannot find the file 'C:\TFS\Builds\Agent404_01\1\s\Acidizing\Model.Techlog\PumpingScheduleSerializerService.cpp', skipping violations
2016-07-29T16:39:38.0071800Z DEBUG: RATS issues processed = 0
```

Wondering if it can be disable so the build runs?

**Comment by jmecosta** [comment]
you mean disable the crash because of invalid file? if so thats from the cxx plugin side, and imo it should crash the analysis if file is invalid.  but you can raise issue in cxx plugin, perhaps others share different opinion.

regarding the path issues, ive seen in our setup some inconsistencies regarding paths. the Solution path given to the runner is starting also like C:\TFS so they match from both sides. 

in a particular issue of ours, we were using git and upon checkout some paths were not created with the correct casing causing this also.

**Comment by jmecosta** [comment]
@Jonathan34 please reopen if still something to discuss
