### ISSUE TITLE
 Could not create SSL/TLS secure channel. 

### ISSUE THREAD

**Issue by sawilde** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#59]
https://ci.appveyor.com/project/sawilde/opencover/build/4.6.721

```` 
    [exec] [EndPhase] : Check Analysis Results in Server every 2 seconds
     [exec] [SERVER CALL] https://sonarqube.com/api/ce/task?id=AVvc72IYmCyt_j31In3y
     [exec] Exception During Run: The request was aborted: Could not create SSL/TLS secure channel. 
     [exec]     at System.Net.HttpWebRequest.GetResponse()
     [exec]    at HelpersMethods.GetRequest(String username, String password, String url) in O:\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\HelpersMethods.fs:line 29
     [exec]    at SonarRunnerPhases.loopTimerCheck@384.Invoke(Unit unitVar0) in O:\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\SonarRunnerPhases.fs:line 384
     [exec]    at SonarRunnerPhases.EndPhase(OptionsData options) in O:\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\SonarRunnerPhases.fs:line 465
     [exec]    at Program.main(String[] argv) in O:\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\Program.fs:line 49
````

**Comment by jmecosta** [comment]
alright, i dont think i ever tried this over a https server. need to investigate this. thanks for reporting

**Comment by jmecosta** [comment]
@sawilde thanks for the fix, ive apply this to the external sonarestservice lib, thanks
