### ISSUE TITLE
Need help running local analysis

### ISSUE THREAD

**Issue by hobeygo** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#64]
Hi,

I have installed VSSonarExtensionMetroVs2017.vsix to integrate VSSonarQube with Visual Studio 2017.

During the initial installation phase, I get the following error from VSSonarQube output and local analysis fail.

I suspect the download location is either changed or my workstation is not able to connect to the location for some reason. (https://github.com/SonarSource/sonar-msbuild-runner/releases/download/3.0.2.656/MSBuild.SonarQube.Runner-3.0.2.656.zip)

Thanks

```
CMD: [D:\Git_Repos\eShopOnWeb] C:\ProgramData\VSSonarExtension\Wrapper\1.9.17\CxxSonarQubeMsbuidRunner.exe /d:sonar.host.url=xxx /d:sonar.login=xxxxx /d:sonar.password=xxxxx /k=your.organization.eShopOnWeb:master /r=3.0.2.656 /m=D:\Git_Repos\eShopOnWeb\eShopOnWeb.sln /n=eShopOnWeb /x=vs17 /p:Configuration=Debug /p:Platform="Any CPU" /d:sonar.analysis.mode=issues /d:sonar.issuesReport.html.enable=true /d:sonar.preview.excludePlugins="devcockpit,pdfreport,report,scmactivity,views,jira,scmstats"
Download and install msbuild runner from github, make sure you have access to Internet or use settings in home folder to specify a external location
Download https://github.com/SonarSource/sonar-msbuild-runner/releases/download/3.0.2.656/MSBuild.SonarQube.Runner-3.0.2.656.zip
Download https://github.com/SonarSource/sonar-msbuild-runner/releases/download/3.0.2.656/sonar-scanner-msbuild-3.0.2.656.zip
Download https://github.com/SonarSource/sonar-msbuild-runner/releases/download/3.0.2.656/MSBuild.SonarQube.Runner.3.0.2.656.zip
Exception During Run: Unable to download and unzip file from github : https://github.com/SonarSource/sonar-msbuild-runner/releases/download/3.0.2.656/MSBuild.SonarQube.Runner-3.0.2.656.zip 
    at InstallationModule.InstallMsbuildRunner$cont@113(String version, Unit unitVar) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\InstallationModule.fs:line 132
   at Options.OptionsData.ConfigureMsbuildRunner() in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\Options.fs:line 392
   at Program.main(String[] argv) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\Program.fs:line 34

```

**Comment by hobeygo** [comment]
Also when I try downloading the MsBuildRunner manually & pass the location to the script through  cxx-user-options.xml file, I get an access denied error. ( I am sure the runner directory is accessable by the script)

```
CMD: [D:\Git_Repos\eShopOnWeb] C:\ProgramData\VSSonarExtension\Wrapper\1.9.17\CxxSonarQubeMsbuidRunner.exe /d:sonar.host.url=http://gitlabtest.rsnet2.com.tr:9000 /d:sonar.login=xxxxx /d:sonar.password=xxxxx /k=your.organization.eShopOnWeb:master /r=3.0.2.656 /m=D:\Git_Repos\eShopOnWeb\eShopOnWeb.sln /n=eShopOnWeb /x=vs17 /p:Configuration=Debug /p:Platform="Any CPU" /d:sonar.analysis.mode=issues /d:sonar.issuesReport.html.enable=true /d:sonar.preview.excludePlugins="devcockpit,pdfreport,report,scmactivity,views,jira,scmstats"
Apply the following changes to sonar configuration Files
###################################
########## Begin Stage  ###########
###################################
[Execute] : D:\SonarQube\bin begin /d:sonar.host.url=xxxxx /k:your.organization.eShopOnWeb:master /n:eShopOnWeb /v: /d:sonar.analysis.mode=issues /d:sonar.issuesReport.html.enable=true /d:sonar.preview.excludePlugins=devcockpit,pdfreport,report,scmactivity,views,jira,scmstats /s:"C:\Users\Administrator\AppData\Local\Temp\tmp99A3.tmp" 

Exception During Run: Access is denied 
    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at MsbuildUtilityHelpers.CommandExecutor.MsbuildUtilityHelpers-ICommandExecutor-ExecuteCommand(String program, String args, FSharpMap`2 env, FSharpFunc`2 outputHandler, FSharpFunc`2 errorHandler, String workingDir) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\Common\MsbuildTaskUtils\IExecutor.fs:line 216
   at Program.main(String[] argv) in E:\Development\SonarQube\jmecsoftware\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\Program.fs:line 39
```

**Comment by jmecosta** [comment]
try using version 4.0.2.892 

https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip 

that should match with

Download https://github.com/SonarSource/sonar-msbuild-runner/releases/download/3.0.2.656/sonar-scanner-msbuild-3.0.2.656.zip

**Comment by hobeygo** [comment]
OK, apparently I was not able to give the full path for MsbuildRunnerPath in cxx-user-options.xml, hence the "Access is denied" error.

Thanks for help
