### ISSUE TITLE
Crash of CxxSonarQubeRunner during end phase

### ISSUE THREAD

**Issue by zabulus** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#69]
```
29-Jan-2020 03:18:04 | [1/29/2020 3:18:04 AM]: ###################################
29-Jan-2020 03:18:04 | [1/29/2020 3:18:04 AM]: ########### Gate Check  ###########
29-Jan-2020 03:18:04 | [1/29/2020 3:18:04 AM]: ###################################
29-Jan-2020 03:18:04 |  
29-Jan-2020 03:18:04 | [1/29/2020 3:18:04 AM]: STATUS: ERROR
29-Jan-2020 03:18:04 |  
29-Jan-2020 03:18:07 |  
29-Jan-2020 03:18:12 | Exception During Run: Object reference not set to an instance of an object.
29-Jan-2020 03:18:12 | at SonarRunnerPhases.loopTimerCheck$cont@527-1(IJsonDocument response, Unit unitVar) in d:\workshop\CxxSonarQubeRunner\CxxSonarQubeRunner\SonarRunnerPhases.fs:line 535
29-Jan-2020 03:18:12 | at SonarRunnerPhases.loopTimerCheck$cont@503(OptionsData options, String content, Unit unitVar) in d:\workshop\CxxSonarQubeRunner\CxxSonarQubeRunner\SonarRunnerPhases.fs:line 523
29-Jan-2020 03:18:12 | at SonarRunnerPhases.loopTimerCheck@480(OptionsData options, String username, FSharpRef`1 idAnalysis, FSharpRef`1 urlForChecking, Unit unitVar0) in d:\workshop\CxxSonarQubeRunner\CxxSonarQubeRunner\SonarRunnerPhases.fs:line 502
29-Jan-2020 03:18:12 | at SonarRunnerPhases.EndPhase(OptionsData options) in d:\workshop\CxxSonarQubeRunner\CxxSonarQubeRunner\SonarRunnerPhases.fs:line 562
29-Jan-2020 03:18:13 | at Program.main(String[] argv) in d:\workshop\CxxSonarQubeRunner\CxxSonarQubeRunner\Program.fs:line 65

```

**Comment by zabulus** [comment]
I'll post PR with fix in a couple of days, after fix confirmation

**Comment by jmecosta** [comment]
Sure thanks
